name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    
    - name: Run tests
      run: go test -v ./...
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Release ${{ github.ref }}
          
          ## Installation
          ```bash
          go get github.com/lukcba-developers/gopherkit@${{ github.ref }}
          ```
          
          ## What's Changed
          Please see the [commit history](https://github.com/lukcba-developers/gopherkit/compare/...${{ github.ref }}) for a full list of changes.
        draft: false
        prerelease: false